
spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/theabhishekmandal/config-repo.git
          clone-on-start: true
          default-label: main

redis:
  client:
    nodeAddress:
      -  'redisCluster'
    operationMode: cluster
    encrypted: false
    password: "{awsSecret}:passwordArn"
    sslEnabled: true
    sslEnableEndpointIdentification: false
    sslTrustStore: "redis.jks"
    sslTruststorePassword: "{awsSecret}:sslTruststoreArn"
#  security:
#    user:
#      name:root
#      password:secret
